### ISSUE TITLE
Create a database of submitted water reports

### ISSUE THREAD

**Issue by barrage125** [barrage125/Team-Waterworks#26]
- [ ] create new database table for water reports
- [x] create a model class that holds info about water report
- [ ] coordinate with whoever is doing the submission form to handle WaterReport objects @barrage125 
- [x] @barrage125 needs a number of water reports parameter
- [ ] make sure @omurkcaya can get info out of a WaterReport object to display it
- [ ] make sure @omurkcaya can get a list of all WaterReport objects associated with the current active user

**Comment by aklaussen** [comment]
@barrage125 WaterReport ID numbers will be autogenerated in the constructor using a private field in the class for how many there are. Currently, there is a getter but not a setter. Do you need to be setting IDs yourself for some reason?

**Comment by aklaussen** [comment]
@omurkcaya  - you can use ReportsManager to ask for reports by username, location, or id like this:
`Collection<WaterReport> reports = ReportsManager.getReportsByAuthor(username);`

Not sure what type of collection it'll be yet, that'll depend on @megmay 's implementation on the database end.

See the `WaterReport` class for all the data fields. They all have getters.

**Comment by megmay** [comment]
Hey guys I'm not sure if anyone has been trying to get a hold of me but I haven't been able to find my phone as of this morning and I was out late last night. I've made a few more commits and I'm almost done with the database end of things.

**Comment by megmay** [comment]
If anyone needs to get a hold of me I'm on Google Hangouts (so you can message or call me from there) or you can email me.

**Comment by megmay** [comment]
@aklaussen When trying to figure out if a report already exists (ReportsManager -> isValidReport), is that so users can't enter duplicate reports? If so, what qualifies the report as being a duplicate report? If it's the same type of report in the same location? Can we have multiple purity reports but only one hey there's water here report?

**Comment by megmay** [comment]
Also, are the 3 types of reports water location, historical, and water purity?
