### ISSUE TITLE
Integrate Water Quality Reports into Database

### ISSUE THREAD

**Issue by barrage125** [barrage125/Team-Waterworks#32]
Ensure that the Water Quality Reports are stored and retrieved appropriately.

**Comment by megmay** [comment]
- [x] Create separate tables for Source and Quality Water Reports in DBHelper
- [x] Create new constructor for Quality Water Reports in DBHelper
- [x] make appropriate changes to water report methods so they can/can't be applied to the diff water report types in DBHelper
- [x] Create new methods for water quality reports if needed in DBHelper. Make sure to include methods needed for creating a new quality report from the quality reports activity
- [x] Integrate different authority levels in Users DB
- [x] create clear db method for all tables and integrate into corresponding managers and activities with clear buttons
- [ ] Make sure report number autogenerated by SQLite
- [x] Make sure Managers are the only ones who can view a list of the quality reports
- [x] View Map doesn't show first water report
- [ ] make alternating row colors http://stackoverflow.com/questions/13109840/android-alternate-row-colors-in-listview
