### ISSUE TITLE
Create Water Quality Report Class in Model

### ISSUE THREAD

**Issue by barrage125** [barrage125/Team-Waterworks#34]
Or appropriately integrate it into our pre-existing Water Report class.

And update ReportsMgr

**Comment by megmay** [comment]
- [x] Refactor WaterReport to WaterSourceReport to distinguish the two
- [ ] Fill in WaterPurityReport model class methods similar to the methods in WaterSourceReport and add getters/setters for all instance vars
- [x]  Refactor ReportsManager to WSRManager to distinguish from WPRManager
- [ ] Fill in WPRManager class methods similar to the methods in WSRManager (including proper error handling)
